language: go
go:
- 1.9.x
- tip

os:
- linux
dist: trusty
sudo: false

matrix:
  allow_failures:
  - go: tip

gobuild_args: -v

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - go get
  - go build -o rabbitmq-checker ./...